baseURL = "https://worldbeyondlinux.be/"
languageCode = "en-us"
title = "The world beyond Linux"
theme = "ezhil"

pygmentsstyle = "pastie"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	# Blog subtitle which appears below blog title. Supports markdown.
	subtitle = "My personal blog about Linux, FOSS, personal projects and other things"
	# Number of posts to show in recent posts list (Optional). Defaults to 10.
	recentPostsCount = 10
	# Content types which are excluded from recent posts and archive page (Optional). Defaults to ["page"]
	excludedTypes = ["page"]
	disableDisqusTypes = ["posts"]
	# If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
	featherIconsCDN = true
  # Switch viewing modes automatically
  mode = "auto"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2


[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/boosterl"

# Enable tags.
[taxonomies]
   tag = "tags"
